name: CI

on:
  push:
    branches: [ thesis ]
  pull_request:
    branches: [ thesis ]

  workflow_dispatch:

jobs:
  build:
    name: Build thesis PDFs
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }

    steps:
      - uses: actions/checkout@v2
      - name: Build the thesis
        run: apt-get update && apt install -y --no-install-recommends make rsync pandoc && cd thesis; make;
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Thesis
          path: |
            thesis/build/*.pdf

  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build
    container: { image: 'ghcr.io/mff-cuni-cz/cuni-thesis-validator' }

    steps:
      - name: Get PDFs
        uses: actions/download-artifact@v3
      - name: Run VeraPDF
        run: verify Thesis/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0"'
